name: Run Relayer Sniper

on:
  schedule:
    # 06:15 UTC corrispondono alle 07:15 Italiane (ora solare)
    # Il bot partirà 30 minuti prima dello snapshot per essere pronto
    - cron: '15 6 * * 1' 
  workflow_dispatch: # Ti permette di lanciarlo a mano dall'app se serve

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-python: '3.9'

      - name: Install dependencies
        run: pip install web3 requests eth-account

      - name: Run Sniper
        env:
          VECHAIN_PRIVATE_KEY: ${{ secrets.VECHAIN_PRIVATE_KEY }}
        run: python bot.py
